# log-level: 2
# log-json: false
# log-file: ""
# listen: ":8080"
# server-crt: ""
# server-key: ""
# upstream: ""
# upstream-cors: ""
# forward-userinfo: false
# forward-access-token: false
# session-lifetime: 5
# client-id: ""
# client-secret: ""
# scopes: []
# redirect-url: ""
# auth-url: ""
# token-url: ""
# userinfo-url: ""
# state-lifetime: 5
# saml-metadata-url: ""
# self-root-url: ""
# whitelist-rule: []