# log-level: 2
# log-json: false
# log-file: ""
# listen: ":8080"
# server-crt: ""
# server-key: ""
# upstream: ""
# upstream-cors: false
# forward-userinfo: false
# forward-access-token: false
# session-lifetime: 5
# client-id: ""
# client-secret: ""
# scopes: []
# redirect-url: ""
# auth-url: ""
# token-url: ""
# userinfo-url: ""
# state-lifetime: 5
# saml-metadata-url: ""
# saml-register-url: ""
# self-root-url: ""
# saml-crt: ""
# saml-key: ""
# ds-base-dn: ""
# ds-bind-dn: ""
# ds-port: 389
# ds-host: ""
# ds-bind-password: ""
# ds-filter: ""
# rules: []
# rules:
# - type: ""
#   method: []
#   path: ""